from utils.formatters import (
    converter_data_completa_para_iso,
    converter_data_humana_para_iso,
)

config = {"linha_inicial": 7, "planilha": "Vendas BR"}

map = {
    0: {"key": "sale_id", "transform": str},
    1: {"key": "sale_date", "transform": converter_data_completa_para_iso},
    2: {"key": "state", "transform": str},
    3: {"key": "status_description", "transform": str},
    4: {"key": "multi_product_package", "transform": str},
    5: {"key": "belongs_to_kit", "transform": str},
    6: {"key": "units", "transform": int},
    7: {"key": "product_revenue", "transform": float},
    8: {"key": "price_increase_revenue", "transform": float},
    9: {"key": "installment_fee", "transform": float},
    10: {"key": "sales_fee_and_taxes", "transform": float},
    11: {"key": "shipping_revenue", "transform": float},
    12: {"key": "shipping_fees", "transform": float},
    13: {"key": "refunds", "transform": float},
    14: {"key": "total_amount", "transform": float},
    15: {"key": "billing_month", "transform": str},
    16: {"key": "ads_sale", "transform": str},
    17: {"key": "sku", "transform": str},
    18: {"key": "listing_id", "transform": str},
    19: {"key": "sales_channel", "transform": str},
    20: {"key": "listing_title", "transform": str},
    21: {"key": "variation", "transform": str},
    22: {"key": "unit_price", "transform": float},
    23: {"key": "listing_type", "transform": str},
    24: {"key": "nfe_attached", "transform": str},
    25: {"key": "personal_or_company_data", "transform": str},
    26: {"key": "document_type_number", "transform": str},
    27: {"key": "address", "transform": str},
    28: {"key": "taxpayer_type", "transform": str},
    29: {"key": "state_registration", "transform": str},
    30: {"key": "buyer_name", "transform": str},
    31: {"key": "business", "transform": str},
    32: {"key": "cpf", "transform": str},
    33: {"key": "buyer_address", "transform": str},
    34: {"key": "city", "transform": str},
    35: {"key": "buyer_state", "transform": str},
    36: {"key": "postal_code", "transform": str},
    37: {"key": "country", "transform": str},
    38: {"key": "delivery_method", "transform": str},
    39: {"key": "delivery_shipped_date", "transform": converter_data_humana_para_iso},
    40: {"key": "delivery_delivered_date", "transform": converter_data_humana_para_iso},
    41: {"key": "delivery_driver", "transform": str},
    42: {"key": "delivery_tracking_number", "transform": str},
    43: {"key": "delivery_tracking_url", "transform": str},
    44: {"key": "return_units", "transform": str},
    45: {"key": "return_method", "transform": str},
    46: {"key": "return_shipped_date", "transform": str},
    47: {"key": "return_delivered_date", "transform": str},
    48: {"key": "return_driver", "transform": str},
    49: {"key": "return_tracking_number", "transform": str},
    50: {"key": "return_tracking_url", "transform": str},
    51: {"key": "reviewed_by_ml", "transform": str},
    52: {"key": "review_date", "transform": str},
    53: {"key": "money_released", "transform": str},
    54: {"key": "result", "transform": str},
    55: {"key": "destination", "transform": str},
    56: {"key": "result_reason", "transform": str},
    57: {"key": "complaint_units", "transform": str},
    58: {"key": "complaint_opened", "transform": str},
    59: {"key": "complaint_closed", "transform": str},
    60: {"key": "mediation", "transform": str},
}
