import { dataParaISO, parseToISO, parseToFloat } from "../utils/normalizers.js";

export const sales_map = {
    "__EMPTY": "sale_id",
    "__EMPTY_1": "sale_date",
    "__EMPTY_2": "state",
    "__EMPTY_3": "status_description",
    "__EMPTY_4": "multi_product_package",
    "__EMPTY_5": "belongs_to_kit",
    "__EMPTY_6": "units",
    "__EMPTY_7": "product_revenue",
    "__EMPTY_8": "price_increase_revenue",
    "__EMPTY_9": "installment_fee",
    "__EMPTY_10": "sales_fee_and_taxes",
    "__EMPTY_11": "shipping_revenue",
    "__EMPTY_12": "shipping_fees",
    "__EMPTY_13": "refunds",
    "__EMPTY_14": "total_amount",
    "__EMPTY_15": "billing_month",
    "__EMPTY_16": "ads_sale",
    "__EMPTY_17": "sku",
    "__EMPTY_18": "listing_id",
    "__EMPTY_19": "sales_channel",
    "__EMPTY_20": "listing_title",
    "__EMPTY_21": "variation",
    "__EMPTY_22": "unit_price",
    "__EMPTY_23": "listing_type",
    "__EMPTY_24": "nfe_attached",
    "__EMPTY_25": "personal_or_company_data",
    "__EMPTY_26": "document_type_number",
    "__EMPTY_27": "address",
    "__EMPTY_28": "taxpayer_type",
    "__EMPTY_29": "state_registration",
    "__EMPTY_30": "buyer_name",
    "__EMPTY_31": "business",
    "__EMPTY_32": "cpf",
    "__EMPTY_33": "buyer_address",
    "__EMPTY_34": "city",
    "__EMPTY_35": "buyer_state",
    "__EMPTY_36": "postal_code",
    "__EMPTY_37": "country",
    "__EMPTY_38": "delivery_method",
    "__EMPTY_39": "delivery_shipped_date",
    "__EMPTY_40": "delivery_delivered_date",
    "__EMPTY_41": "delivery_driver",
    "__EMPTY_42": "delivery_tracking_number",
    "__EMPTY_43": "delivery_tracking_url",
    "__EMPTY_44": "return_units",
    "__EMPTY_45": "return_method",
    "__EMPTY_46": "return_shipped_date",
    "__EMPTY_47": "return_delivered_date",
    "__EMPTY_48": "return_driver",
    "__EMPTY_49": "return_tracking_number",
    "__EMPTY_50": "return_tracking_url",
    "__EMPTY_51": "reviewed_by_ml",
    "__EMPTY_52": "review_date",
    "__EMPTY_53": "money_released",
    "__EMPTY_54": "result",
    "__EMPTY_55": "destination",
    "__EMPTY_56": "result_reason",
    "__EMPTY_57": "complaint_units",
    "__EMPTY_58": "complaint_opened",
    "__EMPTY_59": "complaint_closed",
    "__EMPTY_60": "mediation"
};

export const nfes_map = {
    "Status": "status",
    "Venda/Remessa": "sale_or_dispatch",
    "Numero da NF-e": "invoice_number",
    "Série": "series",
    "Nome": "customer_name",
    "Chave da NFe": "nfe_key",
    "Modalidade": "modality",
    "Operação": "operation",
    "Tipo Logístico": "logistic_type",
    "Emissão": "issue_date",
    "Valor": "amount",
    "Valor Total": "total_amount",
    "Frete": "freight",
    "Observação": "notes"
};

export const sales_normalizer = {
    "sale_date": dataParaISO
}

export const nfes_normalizer = {
    "issue_date": parseToISO,
    "amount": parseToFloat,
    "total_amount": parseToFloat,
    "freight": parseToFloat,
}